### ISSUE TITLE
No message on failed registration 

### ISSUE THREAD

**Issue by imujjwal96** [imujjwal96/prelimQuiz#24]
When a user tries to register with an already taken username or email, registration fails, but the user is not shown any failed message.

### Expected Response
Flash message displaying the error

**Comment by LiamNorman** [comment]
Hey assign this to me please. I'll add this. do you have any flash messaging at the moment in other areas @imujjwal96 ?

**Comment by imujjwal96** [comment]
Sure.
Yes! there is flash messaging in others areas.

**Comment by LiamNorman** [comment]
Hey I've submitted a solution, also added a defensiveness check in the Config class. Let me know what you think?
