### ISSUE TITLE
Unknown collation: 'utf_unicode_ci'

### ISSUE THREAD

**Issue by arpitn30** [imujjwal96/prelimQuiz#9]
After submission of the installation form, the error "Unknown collation: 'utf_unicode_ci'" is encountered and displayed.
![1](https://cloud.githubusercontent.com/assets/14943372/19221147/17ad4ca4-8e5b-11e6-8c99-7b2cdc44b3fb.png)
![2](https://cloud.githubusercontent.com/assets/14943372/19221148/17e46f54-8e5b-11e6-81fa-0e04782157ad.png)

**Comment by imujjwal96** [comment]
The error was due to a silly mistake in the SQL statement. The correct collation was 'utf8_unicode_ci'.
@arpitn30

**Comment by arpitn30** [comment]
Oh lol
